name: Generate Snake

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository content
      - name: Checkout
        uses: actions/checkout@v2

      # Generate the snake game from a GitHub user contributions graph
      # Generate a snake game from a github user contributions graph, output a svg animation at a github page
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: Thalesrup # Substitua pelo seu nome de usuário
          outputs: dist/snake.svg

      - name: Push Snake Game to the repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
